id: I66746E46
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:06:28+00:00'
last_modified: '2022-06-08T13:34:16.789543+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17057
  title: གྲུབ་ཆེན་བརྒྱད་ཅུ་རྩ་བཞིའི་རྣམ་ཐར་དང་དོན་ཧ་འགྲེལ་པ་དང་བཅས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D57D:
      image_group_id: I1KG18472
      title: ''
      total_pages: 290
      order: 1
      base_file: D57D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
